### ISSUE TITLE
Build `nhost start` for Self-Hosted Environments

### ISSUE THREAD

**Issue by mrinalwahal** [nhost/cli#116]
The CLI, as of `v0.5.6` only works with locally spawned services (Hasura, DB, SMTP and Buckets) by default. This doesn't suit well for those users who want to self-host the Nhost stack for custom production.

We can solve this by adding remote credentials (for self-hosted services) in `nhost/config.yaml` file, and launching default services (Hasura, Functions, Auth & Storage) using the same credentials.

In initial versions of this feature, following services can be safely removed from local stack:

1. Database (Postgres)
2. Buckets (S3)
3. SMTP Server

**Timeline Expectation**

The current design of the CLI safely allows us to add this command. We don't necessarily need to "develop" any new feature over here. We mostly just need to "enable" it. So, I'd say, it can safely be achieved within a week's time of development and testing.

**Release Milestone**

Should be kept lower on priority than most other v2.1 features.

**Comment by mrinalwahal** [comment]
We've added the capability of outsourcing, or connecting to remote services, in CLI `v0.6`.

Services that can be outsourced: postgres, minio/S3 and SMTP server.

I'll shortly post here the link to a help guide on how to use the new CLI capabilities for self-hosting your own Nhost environment.

**Comment by c-nv-s** [comment]
> I'll shortly post here the link to a help guide on how to use the new CLI capabilities for self-hosting your own Nhost environment.

**Comment by c-nv-s** [comment]
@mrinalwahal is it possible to acknowledge if this self-hosting guide is still in the pipeline, or has it been overtaken by some other thing?

**Comment by mrinalwahal** [comment]
Hey @c-nv-s, try the following:

In your `nhost/config.yaml`, add the address of your Hasura/Postgres/Minio services.

```
  hasura:
    address: https://your-own-hasura-instance-address:[port] # <- Add this line
    environment:
      hasura_graphql_enable_remote_schema_permissions: false
```

Similarly, add address strings to postgres and minio. And specifically for minio, you can also use an S3 compatible API.

```
  postgres:
    address: postgres://usernama@password:your-postgres-address:[port]/postgres # <- Add this line
    environment:
      postgres_password: postgres
      postgres_user: postgres

  minio:
    address: https://your-own-S3-address:[port] # <- Add this line
    environment:
      minio_root_password: minioaccesskey123123
      minio_root_user: minioaccesskey123123
```

You are allowed to connect to any remotely hosted instances of only the aforementioned 3 services.

Let me know if it works out!
