### ISSUE TITLE
Include minio for storage support

### ISSUE THREAD

**Issue by elitan** [nhost/cli#13]
Add minio as docker service:

```
  nhost-minio:
    image: minio/minio
    restart: always
    volumes:
      - '../minio_data:/export'
    environment:
      MINIO_ACCESS_KEY: <generated_access_key>
      MINIO_SECRET_KEY: <generated_secret_key>
    entrypoint: sh
    command: '-c ''mkdir -p /export/nhost && /usr/bin/minio server /export'''
```

Also add these env var to HBP:

```
      S3_ACCESS_KEY_ID: <generated_access_key>
      S3_SECRET_ACCESS_KEY: <generated_secret_key>
      S3_ENDPOINT: nhost-minio
      S3_BUCKET: nhost
```
