### ISSUE TITLE
can't define environment variables in a simple way

### ISSUE THREAD

**Issue by plmercereau** [nhost/cli#159]
I want to add a secret environment variable (Oauth secret) to `hasura-auth` without storing it to `config.yaml`:

- tried putting it in `.env.development` -> not injected in all containers as per the "documentation" but only in the hasura container
- tried `.env` -> ditto
- tried also the following -> not interpolated
```yaml
services:
  auth:
    environment:
      AUTH_PROVIDER_GITHUB_CLIENT_SECRET: $GITHUB_CLIENT_SECRET
```

Three possible approaches:
1. inject `.env.development` variables in all containers as per the wiki
2. interpolate environment variables from `.env` (why `.env.development`?) in `config.yaml`:
```yaml
auth:
  provider:
      enabled: true
      client_id: "$GITHUB_CLIENT_ID"
      client_secret: "$GITHUB_CLIENT_SECRET"
```
3. Add a `--set` arg to the CLI similar to [Helm](https://helm.sh/docs/chart_template_guide/values_files/)

Without this ability, it is not possible to both store secrets safely and keep `config.yaml` in sync in a git repo.
Maybe there's another way to solve my current issue without changing the code, but I wouldn't know how.
