### ISSUE TITLE
Inconsistent metadata makes the CLI fail when upgrading hasura-auth from `v0.3.2`

### ISSUE THREAD

**Issue by plmercereau** [nhost/cli#173]
Since Hasura Auth [v0.4.0](https://github.com/nhost/hasura-auth/releases/tag/v0.4.0), the `auth.provider_requests.redirect_url` column has been removed.

But as this column is still mentioned in the local metadata in `nhost/metadata/databases/default/tables/auth_provider_requests.yaml`, the Nhost CLI will fail to apply metadata. It is worth mentioning this error will most likely hamper the ability to use hasura-auth versions above `v0.3.2`.

To run `hasura metadata inconsistency drop` before running `hasura metadata apply` will likely solve the issue

In the meantime, it is possible to manually solve the problem in modifying the local file `nhost/metadata/databases/default/tables/auth_provider_requests.yaml`:

Before:
```yaml
...
configuration:
  custom_column_names:
    redirect_url: redirectUrl
...
```

After:
```yaml
...
configuration:
  custom_column_names: {}
...
```

To reproduce:
Nhost CLI version: `v0.6.2`
1. Create an empty Nhost project
2. Start the project
3. Stop the project
4. Upgrade Hasura Auth in `nhost/config.yaml`:
```yaml
services:
  auth:
    version: 0.5.0
```
5. Start the project again
