### ISSUE TITLE
Storage Fails when custom Postgres address is provided

### ISSUE THREAD

**Issue by andr-ec** [nhost/cli#202]
**Describe the bug**
The top of my config.yaml looks like this: 
```
services:
  hasura:
    environment:
      hasura_graphql_enable_remote_schema_permissions: false
      hasura_graphql_database_url: postgres://postgres:1234@172.19.0.1:5432/my_database?sslmode=disable
  minio:
    environment:
      minio_root_password: minioaccesskey123123
      minio_root_user: minioaccesskey123123
  postgres:
    address: postgres://postgres:1234@172.19.0.1:5432/my_database?sslmode=disable
    environment:
      postgres_password: postgres
      postgres_user: postgres
  auth:
    environment:
      hasura_graphql_database_url: postgres://postgres:1234@172.19.0.1:5432/my_database?sslmode=disable
  storage:
    environment:
      hasura_graphql_database_url: postgres://postgres:1234@172.19.0.1:5432/my_database?sslmode=disable
      postgres_migrations_source: postgres://postgres:1234@172.19.0.1:5432/my_database?sslmode=disable
      database_url: postgres://postgres:1234@172.19.0.1:5432/my_database?sslmode=disable
```

I am providing an address in the Postgres section, so that I can use my local database instead of the docker instance.

But storage fails the health check because it doesn't use the Postgres address provided, or the environment variable in the serve command.

`docker inspect` gives the following:
```
 "Cmd": [
                "serve",
                "--postgres-migrations",
                "--postgres-migrations-source",
                "postgres://postgres:postgres@nhost_postgres:5602/postgres?sslmode=disable",
                "--hasura-metadata",
                "--hasura-admin-secret",
                "nhost-admin-secret",
                "--hasura_endpoint",
                "http://nhost_hasura:9212/v1",
                "--bind",
                ":8552",
                "--public-url",
                "http://localhost:8552"
            ],
```

Which shows it ignores the postgres.address field and uses `nhost_postgres` instead for `--postgres-migrations-source`

**To Reproduce**
Run a Postgres database locally. 

Add the following line in the bottom of pg_hba.conf:

`hostnossl    all          all            0.0.0.0/0  trust`
Add/modify the line in postgresql.conf:

`listen_addresses = '*'`

Restart postgres

Create the auth and storage schemas in the database.

Update yaml.config. to use this database. 

`nhost dev --debug`

**Expected behavior**

Storage command uses postges address value for `--postgres-migrations-source`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version v0.6.6

**Additional context**

The problem is in this function:

https://github.com/nhost/cli/blob/e7ec9f3108c41c5d7cc9df77bd851a2a4606bc41/nhost/nhost.go#L479

Which doesn't reach `s.Address` by the time the serve command for storage is run. Because by this point `s.Name` will be equal to `GetContainerName("postgres")`. This issue doesn't happen with auth.

Possible solutions:
Use config.Services["postgres"].Address instead of `GetAddress(config.Services["postgres"])` here:
https://github.com/nhost/cli/blob/e7ec9f3108c41c5d7cc9df77bd851a2a4606bc41/nhost/nhost.go#L988

If `s.Address` has a value, always use it. Instead of checking for `s.Name`
https://github.com/nhost/cli/blob/e7ec9f3108c41c5d7cc9df77bd851a2a4606bc41/nhost/nhost.go#L480-L490

Happy to submit a PR with whichever method is preferred.
