### ISSUE TITLE
the default `config.toml` doesn't contain the right structure for `allowed_redirect_urls`

### ISSUE THREAD

**Issue by linden** [nhost/cli#332]
currently the structure looks like this:
```yaml
auth:
  access_control:
    [...]
    url:
      allowed_redirect_urls: "https://google.com/"
```

when it should look like this:
```yaml
auth:
  access_control:
    [...]
    allowed_redirect_urls: "https://google.com/"
```

this does not cause an error and fails silently.

[discussion on discord](https://discord.com/channels/552499021260914688/1016107419543285901/1016415320736551052).
