### ISSUE TITLE
Cannot start nhost cli

### ISSUE THREAD

**Issue by Andrew-Bekhiet** [nhost/cli#373]
Whenever I run ```nhost up``` I run into errors that seem weird

Output of ```sudo nhost up --debug```
```
> Initializing Hasura client
> start timeout is set to 10m0s
> Stopping docker compose


> [port 5432 is not available, use --db-port flag to provide another one] Failed to start services
> Stopping docker compose

```

But port 5432 is available, and even when I specify different port:

Output of ```sudo nhost up --debug --db-port 5430```:
```
> Initializing Hasura client
> start timeout is set to 10m0s
> Stopping docker compose
> Starting docker compose
> Starting functions
> Starting postgres, graphql-engine containers...
> Start took 1.866015349s


> [exit status 1
Container test-focused_goldstine-postgres-1  Creating
Container test-focused_goldstine-postgres-1  Created
Container test-focused_goldstine-graphql-engine-1  Creating
Container test-focused_goldstine-graphql-engine-1  Created
Container test-focused_goldstine-postgres-1  Starting
Container test-focused_goldstine-postgres-1  Started
Container test-focused_goldstine-postgres-1  Waiting
container for service "postgres" is unhealthy
] Failed to start services
> Stopping docker compose

```

Also I can't find any documentation about where I can find nhost logs or its docker compose logs
To reproduce just run ```nhost init``` type an app name then ```nhost up```

**Comment by elephant3** [comment]
Hello and thanks for reporting 👋 

Please let me know the OS you're using.

Logs can be read via `nhost logs`, it has a few flags, check out `nhost logs --help`. For checking db logs I'd run in separate terminal tab `nhost logs -f postgres` and then run `nhost up -d`.

If issue persists, you can try to remove `.nhost` folder in the root of the project (which would also erase database state) and retry `nhost up`

**Comment by Andrew-Bekhiet** [comment]
Kali Linux

Output of ```nhost logs -f postgres```:

```
test-amazing_lederberg-postgres-1  | Resolving pg_hba.conf
test-amazing_lederberg-postgres-1  | The files belonging to this database system will be owned by user "postgres".
test-amazing_lederberg-postgres-1  | This user must also own the server process.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | The database cluster will be initialized with locale "en_US.UTF-8".
test-amazing_lederberg-postgres-1  | The default database encoding has accordingly been set to "UTF8".
test-amazing_lederberg-postgres-1  | The default text search configuration will be set to "english".
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | Data page checksums are disabled.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
test-amazing_lederberg-postgres-1  | creating subdirectories ... ok
test-amazing_lederberg-postgres-1  | selecting dynamic shared memory implementation ... posix
test-amazing_lederberg-postgres-1  | selecting default max_connections ... 20
test-amazing_lederberg-postgres-1  | selecting default shared_buffers ... 400kB
test-amazing_lederberg-postgres-1  | selecting default time zone ... Etc/UTC
test-amazing_lederberg-postgres-1  | creating configuration files ... ok
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:28.212 UTC [84] FATAL:  data directory "/var/lib/postgresql/data/pgdata" has wrong ownership
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:28.212 UTC [84] HINT:  The server must be started by the user that owns the data directory.
test-amazing_lederberg-postgres-1  | child process exited with exit code 1
test-amazing_lederberg-postgres-1  | initdb: removing contents of data directory "/var/lib/postgresql/data/pgdata"
test-amazing_lederberg-postgres-1 exited with code 1
test-amazing_lederberg-postgres-1  | Resolving pg_hba.conf
test-amazing_lederberg-postgres-1  | The files belonging to this database system will be owned by user "postgres".
test-amazing_lederberg-postgres-1  | This user must also own the server process.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | The database cluster will be initialized with locale "en_US.UTF-8".
test-amazing_lederberg-postgres-1  | The default database encoding has accordingly been set to "UTF8".
test-amazing_lederberg-postgres-1  | The default text search configuration will be set to "english".
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | Data page checksums are disabled.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
test-amazing_lederberg-postgres-1  | creating subdirectories ... ok
test-amazing_lederberg-postgres-1  | selecting dynamic shared memory implementation ... posix
test-amazing_lederberg-postgres-1  | selecting default max_connections ... 20
test-amazing_lederberg-postgres-1  | selecting default shared_buffers ... 400kB
test-amazing_lederberg-postgres-1  | selecting default time zone ... Etc/UTC
test-amazing_lederberg-postgres-1  | creating configuration files ... ok
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:28.212 UTC [84] FATAL:  data directory "/var/lib/postgresql/data/pgdata" has wrong ownership
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:28.212 UTC [84] HINT:  The server must be started by the user that owns the data directory.
test-amazing_lederberg-postgres-1  | child process exited with exit code 1
test-amazing_lederberg-postgres-1  | initdb: removing contents of data directory "/var/lib/postgresql/data/pgdata"
test-amazing_lederberg-postgres-1  | running bootstrap script ... Resolving pg_hba.conf
test-amazing_lederberg-postgres-1  | The files belonging to this database system will be owned by user "postgres".
test-amazing_lederberg-postgres-1  | This user must also own the server process.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | The database cluster will be initialized with locale "en_US.UTF-8".
test-amazing_lederberg-postgres-1  | The default database encoding has accordingly been set to "UTF8".
test-amazing_lederberg-postgres-1  | The default text search configuration will be set to "english".
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | Data page checksums are disabled.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
test-amazing_lederberg-postgres-1  | creating subdirectories ... ok
test-amazing_lederberg-postgres-1  | selecting dynamic shared memory implementation ... posix
test-amazing_lederberg-postgres-1  | selecting default max_connections ... 20
test-amazing_lederberg-postgres-1  | selecting default shared_buffers ... 400kB
test-amazing_lederberg-postgres-1  | selecting default time zone ... Etc/UTC
test-amazing_lederberg-postgres-1  | creating configuration files ... ok
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:28.943 UTC [85] FATAL:  data directory "/var/lib/postgresql/data/pgdata" has wrong ownership
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:28.943 UTC [85] HINT:  The server must be started by the user that owns the data directory.
test-amazing_lederberg-postgres-1  | child process exited with exit code 1
test-amazing_lederberg-postgres-1  | initdb: removing contents of data directory "/var/lib/postgresql/data/pgdata"
test-amazing_lederberg-postgres-1 exited with code 1
test-amazing_lederberg-postgres-1  | Resolving pg_hba.conf
test-amazing_lederberg-postgres-1  | The files belonging to this database system will be owned by user "postgres".
test-amazing_lederberg-postgres-1  | This user must also own the server process.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | The database cluster will be initialized with locale "en_US.UTF-8".
test-amazing_lederberg-postgres-1  | The default database encoding has accordingly been set to "UTF8".
test-amazing_lederberg-postgres-1  | The default text search configuration will be set to "english".
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | Data page checksums are disabled.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
test-amazing_lederberg-postgres-1  | creating subdirectories ... ok
test-amazing_lederberg-postgres-1  | selecting dynamic shared memory implementation ... posix
test-amazing_lederberg-postgres-1  | selecting default max_connections ... 20
test-amazing_lederberg-postgres-1  | selecting default shared_buffers ... 400kB
test-amazing_lederberg-postgres-1  | selecting default time zone ... Etc/UTC
test-amazing_lederberg-postgres-1  | creating configuration files ... ok
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:28.212 UTC [84] FATAL:  data directory "/var/lib/postgresql/data/pgdata" has wrong ownership
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:28.212 UTC [84] HINT:  The server must be started by the user that owns the data directory.
test-amazing_lederberg-postgres-1  | child process exited with exit code 1
test-amazing_lederberg-postgres-1  | initdb: removing contents of data directory "/var/lib/postgresql/data/pgdata"
test-amazing_lederberg-postgres-1  | running bootstrap script ... Resolving pg_hba.conf
test-amazing_lederberg-postgres-1  | The files belonging to this database system will be owned by user "postgres".
test-amazing_lederberg-postgres-1  | This user must also own the server process.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | The database cluster will be initialized with locale "en_US.UTF-8".
test-amazing_lederberg-postgres-1  | The default database encoding has accordingly been set to "UTF8".
test-amazing_lederberg-postgres-1  | The default text search configuration will be set to "english".
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | Data page checksums are disabled.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
test-amazing_lederberg-postgres-1  | creating subdirectories ... ok
test-amazing_lederberg-postgres-1  | selecting dynamic shared memory implementation ... posix
test-amazing_lederberg-postgres-1  | selecting default max_connections ... 20
test-amazing_lederberg-postgres-1  | selecting default shared_buffers ... 400kB
test-amazing_lederberg-postgres-1  | selecting default time zone ... Etc/UTC
test-amazing_lederberg-postgres-1  | creating configuration files ... ok
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:28.943 UTC [85] FATAL:  data directory "/var/lib/postgresql/data/pgdata" has wrong ownership
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:28.943 UTC [85] HINT:  The server must be started by the user that owns the data directory.
test-amazing_lederberg-postgres-1  | child process exited with exit code 1
test-amazing_lederberg-postgres-1  | initdb: removing contents of data directory "/var/lib/postgresql/data/pgdata"
test-amazing_lederberg-postgres-1  | running bootstrap script ... Resolving pg_hba.conf
test-amazing_lederberg-postgres-1  | The files belonging to this database system will be owned by user "postgres".
test-amazing_lederberg-postgres-1  | This user must also own the server process.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | The database cluster will be initialized with locale "en_US.UTF-8".
test-amazing_lederberg-postgres-1  | The default database encoding has accordingly been set to "UTF8".
test-amazing_lederberg-postgres-1  | The default text search configuration will be set to "english".
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | Data page checksums are disabled.
test-amazing_lederberg-postgres-1  | 
test-amazing_lederberg-postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
test-amazing_lederberg-postgres-1  | creating subdirectories ... ok
test-amazing_lederberg-postgres-1  | selecting dynamic shared memory implementation ... posix
test-amazing_lederberg-postgres-1  | selecting default max_connections ... 20
test-amazing_lederberg-postgres-1  | selecting default shared_buffers ... 400kB
test-amazing_lederberg-postgres-1  | selecting default time zone ... Etc/UTC
test-amazing_lederberg-postgres-1  | creating configuration files ... ok
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:29.738 UTC [85] FATAL:  data directory "/var/lib/postgresql/data/pgdata" has wrong ownership
test-amazing_lederberg-postgres-1  | 2022-09-29 22:27:29.738 UTC [85] HINT:  The server must be started by the user that owns the data directory.
test-amazing_lederberg-postgres-1  | child process exited with exit code 1
test-amazing_lederberg-postgres-1  | initdb: removing contents of data directory "/var/lib/postgresql/data/pgdata"
test-amazing_lederberg-postgres-1 exited with code 130
test-amazing_lederberg-postgres-1 exited with code 0
```

I see that it is a permission error so I'm not sure if it is because of my system or the docker container?

This is the first time I use the cli so there is no database state in ```.nhost```, anyway I tried it but it still fails

**Comment by Andrew-Bekhiet** [comment]
After editing ```config.yaml``` and setting pdata:

```
postgres:
  environment:
    PGDATA: ../.nhost/data/master/db/pgdata
```

I had another error with minio:

```
test-amazing_lederberg-postgres-1   | 
test-amazing_lederberg-postgres-1   | PostgreSQL init process complete; ready for start up.
test-amazing_lederberg-postgres-1   | 
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:51.649 UTC () [8] LOG:  starting PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:51.649 UTC () [8] LOG:  listening on IPv4 address "0.0.0.0", port 5432
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:51.649 UTC () [8] LOG:  listening on IPv6 address "::", port 5432
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:51.652 UTC () [8] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:51.655 UTC () [67] LOG:  database system was shut down at 2022-09-29 22:56:51 UTC
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:51.658 UTC () [8] LOG:  database system is ready to accept connections
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.065 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] ERROR:  relation "auth.migrations" does not exist at character 8
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.065 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] STATEMENT:  UPDATE "auth"."migrations"
test-amazing_lederberg-postgres-1   | 	        SET hash='78f76f88eff3b11ebab9be4f2469020dae017110'
test-amazing_lederberg-postgres-1   | 	        WHERE id='5' AND hash='2b4f130ec6284768ac8285d7afb7e4e607c48e70';
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.080 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is already a transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.116 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is no transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.116 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is already a transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.118 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is no transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.118 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is already a transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.120 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is no transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.120 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is already a transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.122 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is no transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.123 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is already a transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.130 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is no transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.130 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is already a transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.132 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is no transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.133 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is already a transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.134 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is no transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.134 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is already a transaction in progress
test-amazing_lederberg-postgres-1   | 2022-09-29 22:56:56.136 UTC (test-amazing_lederberg-auth-1.test-amazing_lederberg_default(56222)) [93] WARNING:  there is no transaction in progress
Error: No such container: a6faf574e238b1dac9997c09dacb55ec151fe54b720c5f768315ad32edda93f8
Error: exit status 1
```
But I disabled it for now and it worked

**Comment by Andrew-Bekhiet** [comment]
My bad! After reinstalling docker the issue is gone

**Comment by elephant3** [comment]
@Andrew-Bekhiet can you share the previous docker version which wasn't working for you? And also the one that you're currently using?

**Comment by Andrew-Bekhiet** [comment]
Oh, Sorry I thought the error was gone because I reinstalled docker and used docker compose directly after replacing postgres service with other postgres instance outside docker (on the host machine), but testing it now looks like the cli is still failing because of postgres

In the two cases I used latest docker version available:
```
Client: Docker Engine - Community
 Cloud integration: v1.0.29
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:12:08 2022
 OS/Arch:           linux/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Here is docker compose file that works with me:
```
version: '3.9'
volumes:
  functions_node_modules:
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:1337"
    ports:
      - "1337:1337"
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  functions:
    image: nhost/functions:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-functions.stripprefix.prefixes=/v1/functions"
      - "traefik.http.routers.functions.rule=Host(`localhost`) && PathPrefix(`/v1/functions`)"
      - "traefik.http.routers.functions.middlewares=strip-functions@docker"
      - "traefik.http.routers.functions.entrypoints=web"
    restart: always
    expose:
      - 3000
    healthcheck:
      disable: true
    volumes:
      - .:/opt/project
      - functions_node_modules:/opt/project/node_modules
      - /opt/project/data/
      - /opt/project/initdb.d/
  
  # postgres:
  #   image: postgres
  #   restart: always
  #   volumes:
  #     - db-data:/var/lib/postgresql/data:Z
  #     - ./initdb.d:/docker-entrypoint-initdb.d:ro
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpgpassword}
  #   ports:
  #     - '5432:5432'

  graphql-engine:
    image: hasura/graphql-engine:v2.12.0
    restart: always
    expose:
      - 8080
    environment:

      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: 'naming_convention'
      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: 'graphql-default'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
      
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@host.docker.internal:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hasura.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.hasura.entrypoints=web"

  mailhog:
    image: mailhog/mailhog
    environment:
      SMTP_HOST: ${AUTH_SMTP_HOST:-mailhog}
      SMTP_PORT: ${AUTH_SMTP_PORT:-1025}
      SMTP_USER: ${AUTH_SMTP_USER:-user}
      SMTP_PASS: ${AUTH_SMTP_PASS:-password}
      SMTP_SECURE: "${AUTH_SMTP_SECURE:-false}"
      SMTP_SENDER: ${AUTH_SMTP_SENDER:-hbp@hbp.com}
    ports:
      - ${AUTH_SMTP_PORT:-1025}:1025
      - 8025:8025
    volumes:
      - ./data/mailhog:/maildir

  auth:
    image: nhost/hasura-auth:latest
    depends_on:
      - graphql-engine
    restart: always
    volumes:
      - ./emails:/app/email-templates
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@host.docker.internal:5432/postgres
      HASURA_GRAPHQL_GRAPHQL_URL: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}

      AUTH_HOST: '0.0.0.0'
      AUTH_CLIENT_URL: ${AUTH_CLIENT_URL:-http://localhost:3000}
      AUTH_SMTP_HOST: ${AUTH_SMTP_HOST:-mailhog}
      AUTH_SMTP_PORT: ${AUTH_SMTP_PORT:-1025}
      AUTH_SMTP_USER: ${AUTH_SMTP_USER:-user}
      AUTH_SMTP_PASS: ${AUTH_SMTP_PASS:-password}
      AUTH_SMTP_SENDER: ${AUTH_SMTP_SENDER:-hbp@hbp.com}
    expose:
      - 4000
    healthcheck:
      disable: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-auth.stripprefix.prefixes=/v1/auth"
      - "traefik.http.routers.auth.rule=Host(`localhost`) && PathPrefix(`/v1/auth`)"
      - "traefik.http.routers.auth.middlewares=strip-auth@docker"
      - "traefik.http.routers.auth.entrypoints=web"
```

After having done more research, looks like it is more of a problem with postgres and docker so I don't know if I should reopen this?

So this works (adding a volume instead of a host folder):
```
version: '3'
volumes:
  functions_node_modules:
  # Added a volume for postgres
  db-data:
services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:1337"
    ports:
      - "1337:1337"
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  functions:
    image: nhost/functions:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-functions.stripprefix.prefixes=/v1/functions"
      - "traefik.http.routers.functions.rule=Host(`localhost`) && PathPrefix(`/v1/functions`)"
      - "traefik.http.routers.functions.middlewares=strip-functions@docker"
      - "traefik.http.routers.functions.entrypoints=web"
    restart: always
    expose:
      - 3000
    healthcheck:
      disable: true
    volumes:
      - .:/opt/project
      - functions_node_modules:/opt/project/node_modules
      - /opt/project/data/
      - /opt/project/initdb.d/
  
  postgres:
    image: postgres
    restart: always
    volumes:
      # Use the new volumn
      - db-data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpgpassword}
    ports:
      - '5432:5432'

  graphql-engine:
    image: hasura/graphql-engine:v2.12.0
    depends_on:
      - postgres
    restart: always
    expose:
      - 8080
    environment:

      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: 'naming_convention'
      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: 'graphql-default'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_TELEMETRY: 'false'
      
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hasura.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.hasura.entrypoints=web"

  mailhog:
    image: mailhog/mailhog
    environment:
      SMTP_HOST: ${AUTH_SMTP_HOST:-mailhog}
      SMTP_PORT: ${AUTH_SMTP_PORT:-1025}
      SMTP_USER: ${AUTH_SMTP_USER:-user}
      SMTP_PASS: ${AUTH_SMTP_PASS:-password}
      SMTP_SECURE: "${AUTH_SMTP_SECURE:-false}"
      SMTP_SENDER: ${AUTH_SMTP_SENDER:-hbp@hbp.com}
    ports:
      - ${AUTH_SMTP_PORT:-1025}:1025
      - 8025:8025
    volumes:
      - ./data/mailhog:/maildir

  auth:
    image: nhost/hasura-auth:latest
    depends_on:
      - postgres
      - graphql-engine
    restart: always
    volumes:
      - ./emails:/app/email-templates
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_GRAPHQL_URL: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}

      AUTH_HOST: '0.0.0.0'
      AUTH_CLIENT_URL: ${AUTH_CLIENT_URL:-http://localhost:3000}
      AUTH_SMTP_HOST: ${AUTH_SMTP_HOST:-mailhog}
      AUTH_SMTP_PORT: ${AUTH_SMTP_PORT:-1025}
      AUTH_SMTP_USER: ${AUTH_SMTP_USER:-user}
      AUTH_SMTP_PASS: ${AUTH_SMTP_PASS:-password}
      AUTH_SMTP_SENDER: ${AUTH_SMTP_SENDER:-hbp@hbp.com}
    expose:
      - 4000
    healthcheck:
      disable: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.strip-auth.stripprefix.prefixes=/v1/auth"
      - "traefik.http.routers.auth.rule=Host(`localhost`) && PathPrefix(`/v1/auth`)"
      - "traefik.http.routers.auth.middlewares=strip-auth@docker"
      - "traefik.http.routers.auth.entrypoints=web"

  minio:
    image: minio/minio:RELEASE.2021-09-24T00-24-24Z
    entrypoint: sh
    command: -c 'mkdir -p /data/nhost && /opt/bin/minio server --address :8484 /data'
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_KEY}
    ports:
      - ${MINIO_PORT:-8484}:8484
    volumes:
      - ./data/minio:/data
  storage:
    image: nhost/hasura-storage:0.2.1
    depends_on:
      - postgres
      - graphql-engine
      - minio
    restart: always
    expose:
      - 8000
    healthcheck:
      disable: true
    environment:
      PUBLIC_URL: http://localhost:${PROXY_PORT:-1337}
      HASURA_METADATA: 1
      HASURA_ENDPOINT: http://graphql-engine:8080/v1
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      S3_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      S3_SECRET_KEY: ${STORAGE_SECRET_KEY}
      S3_ENDPOINT: ${STORAGE_ENDPOINT:-http://minio:8484}
      S3_BUCKET: ${STORAGE_BUCKET:-nhost}
      POSTGRES_MIGRATIONS: 1
      POSTGRES_MIGRATIONS_SOURCE: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres?sslmode=disable
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storage.rule=Host(`localhost`) && PathPrefix(`/v1/storage`)"
      - "traefik.http.routers.storage.entrypoints=web"
      # Rewrite the path so it matches with the new storage API path introduced in hasura-storage 0.2
      - "traefik.http.middlewares.strip-suffix.replacepathregex.regex=^/v1/storage/(.*)"
      - "traefik.http.middlewares.strip-suffix.replacepathregex.replacement=/v1/$$1"
      - "traefik.http.routers.storage.middlewares=strip-suffix@docker"
    command: serve
```
