### ISSUE TITLE
Expose minio 9000 port

### ISSUE THREAD

**Issue by andr-ec** [nhost/cli#766]
It would be great if while developing locally we had the storage minio port 9000 exposed. If we are developing services that need direct access to the storage, we need the docker port for minio exposed.
Something similar to what is done with postgres: 

```yaml
        ports:
            - mode: ingress
              target: 9000
              published: "9000"
              protocol: tcp
```
