### ISSUE TITLE
claims_map should support arrays too

### ISSUE THREAD

**Issue by dbarrosop** [nhost/cli#792]
For reference: https://hasura.io/docs/latest/auth/authentication/jwt/#x-hasura-allowed-roles

A potential solution would be allow passing a json as value, for instance:

```toml
[[hasura.jwtSecrets.claims_map]]
claim = 'x-hasura-allowed-roles'
valueJson = '["user", "something"]'
```

We may want to understand the use case first though as hasura-auth already fills this.
