### ISSUE TITLE
How to make Nhost CLI work in a CI

### ISSUE THREAD

**Issue by alveshelio** [nhost/cli#80]
Right now Nhost CLI. can't run in GitHub actions.

This is my 2e2tests.yml workflow file:
```yaml
name: Cypress Test
on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_GRAPHQL_ENDPOINT: ${{ secrets.NEXT_PUBLIC_GRAPHQL_ENDPOINT }}
      NEXT_PUBLIC_BACKEND_ENDPOINT: ${{ secrets.NEXT_PUBLIC_BACKEND_ENDPOINT }}
      NEXT_PUBLIC_HASURA_SECRET: ${{ secrets.NEXT_PUBLIC_HASURA_SECRET }}
      HASURA_GRAPHQL_ENDPOINT: ${{ secrets.HASURA_GRAPHQL_ENDPOINT }}
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14

      - run: npm install -g yarn
      - run: npm install -g nhost
      - run: npm install -g hasura-cli
      - run: curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - run: chmod +x /usr/local/bin/docker-compose
      - run: nhost dev
      - run: hasura seeds apply --file /03-29-2021-insert-user.sql --admin-secret ${{ secrets.NEXT_PUBLIC_HASURA_SECRET }} --endpoint ${{ secrets.HASURA_GRAPHQL_ENDPOINT }}
      - run: yarn install --frozen-lockfile
      - name: Run cypress tests
        run: npm run e2e:ci

        continue-on-error: false
```

In order to test and debug my workflows locally I'm using a tool called [act](https://github.com/nektos/act)
When running this this workflow locally it fails because Nhost CLI isn't able to create the necessary ressources, these are the errors I get 

[Cypress Test/cypress-test    ] ⭐  Run nhost dev
|
| - Nhost is starting...first run takes longer
| ✖ Nhost is starting...first run takes longer
| Error! Command failed: docker-compose -f ./.nhost/docker-compose.yaml up -d --build
| Creating network "nhost_default" with the default driver
| Creating nhost_minio ...
| Creating nhost_postgres ...
| Creating nhost_postgres ... error
|
| ERROR: for nhost_postgres  Cannot start service nhost-postgres: Mounts denied:
| The path /github/workspace/.nhost/db_data is not shared from the host and is not known to Docker.
| You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
| See https://docs.docker.com/docker-for-mac for more info.
| Creating nhost_minio    ... error
|
| ERROR: for nhost_minio  Cannot start service minio: Mounts denied:
| The path /github/workspace/.nhost/minio/data is not shared from the host and is not known to Docker.
| You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
| See https://docs.docker.com/docker-for-mac for more info.
|
| ERROR: for nhost-postgres  Cannot start service nhost-postgres: Mounts denied:
| The path /github/workspace/.nhost/db_data is not shared from the host and is not known to Docker.
| You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
| See https://docs.docker.com/docker-for-mac for more info.
|
| ERROR: for minio  Cannot start service minio: Mounts denied:
| The path /github/workspace/.nhost/minio/data is not shared from the host and is not known to Docker.
| You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
| See https://docs.docker.com/docker-for-mac for more info.
| Encountered errors while bringing up the project.
|
| Error! Command failed: docker-compose -f ./.nhost/docker-compose.yaml up -d --build
| Creating network "nhost_default" with the default driver
| Creating nhost_minio ...
| Creating nhost_postgres ...
| Creating nhost_postgres ... error
|
| ERROR: for nhost_postgres  Cannot start service nhost-postgres: Mounts denied:
| The path /github/workspace/.nhost/db_data is not shared from the host and is not known to Docker.
| You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
| See https://docs.docker.com/docker-for-mac for more info.
| Creating nhost_minio    ... error
|
| ERROR: for nhost_minio  Cannot start service minio: Mounts denied:
| The path /github/workspace/.nhost/minio/data is not shared from the host and is not known to Docker.
| You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
| See https://docs.docker.com/docker-for-mac for more info.
|
| ERROR: for nhost-postgres  Cannot start service nhost-postgres: Mounts denied:
| The path /github/workspace/.nhost/db_data is not shared from the host and is not known to Docker.
| You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
| See https://docs.docker.com/docker-for-mac for more info.
|
| ERROR: for minio  Cannot start service minio: Mounts denied:
| The path /github/workspace/.nhost/minio/data is not shared from the host and is not known to Docker.
| You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
| See https://docs.docker.com/docker-for-mac for more info.
| Encountered errors while bringing up the project.
|
|
| - stopping Nhost

I guess that for real world projects, having E2E tests this is a must have and I'd love to have my E2E tests running on each PR.

If anyone interested in making Nhost CLI run in the CI, I'd love to help in any way I can.

Thank you
